// All of the redux action types
export const SET_DARK_THEME = 'SET_DARK_THEME';
export const SET_LIGHT_THEME = 'SET_LIGHT_THEME';
export const SET_COLOR_THEME = 'SET_COLOR_THEME';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const UPDATE_FILTER_LOCATION = 'UPDATE_FILTER_LOCATION';
export const UPDATE_FILTER_TYPE = 'UPDATE_FILTER_TYPE';
export const UPDATE_FILTER_COMPANY = 'UPDATE_FILTER_COMPANY';
export const UPDATE_FILTER_CATEGORY = 'UPDATE_FILTER_CATEGORY';
export const SET_RESULTS = 'SET_RESULTS';
export const SAVE_RESUME = 'SAVE_RESUME';
