export const SET_DARK_THEME = "SET_DARK_THEME";
export const SET_LIGHT_THEME = "SET_LIGHT_THEME";
export const SET_COLOR_THEME = "SET_COLOR_THEME";
export const TOGGLE_THEME = "TOGGLE_THEME";
export const SAVE_RESUME = "SAVE_RESUME";